name: utils

services:
  cli:
    image: patrikjak/php-frankenphp:8.5-cli
    container_name: "utils-cli"
    environment:
      XDEBUG_MODE: develop,debug,coverage
    volumes:
      - ".:/var/www"

  node:
    image: node:25-alpine
    container_name: "utils-node"
    volumes:
      - ".:/app"
    working_dir: /app