name: CI

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  lint:
    uses: patrikjak/workflows/.github/workflows/lint.yml@main
    with:
      php-version: '8.5'

  test:
    uses: patrikjak/workflows/.github/workflows/test.yml@main
    with:
      php-version: '8.5'
      codecov-slug: patrikjak/utils
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
